from tkinter import *
import pygame

loop=Tk()
loop.title("Zankyo Player")
loop.iconbitmap("Graphics\\ZankyoIcon2.ico")
loop.geometry("500x400")
loop.configure(bg="#006666")
backg=Listbox(loop,bg="#669999",fg="#00cc99",width=80,bd=5)
backg.pack(pady=10)
pygame.mixer.init()
playimg=PhotoImage(file="Graphics\\Playb.png")
pauseimg=PhotoImage(file="Graphics\\Pauseb.png")
nextimg=PhotoImage(file="Graphics\\Nextb.png")
previmg=PhotoImage(file="Graphics\\Prevb.png")
stopimg=PhotoImage(file="Graphics\\Stopb.png")
imagespace=Frame(loop)
imagespace.pack()
playbt=Button(imagespace,image=playimg,borderwidth=0,bg="#006666")
pausebt=Button(imagespace,image=pauseimg,borderwidth=0,bg="#006666")
prevbt=Button(imagespace,image=previmg,borderwidth=0,bg="#006666")
nextbt=Button(imagespace,image=nextimg,borderwidth=0,bg="#006666")
stopbt=Button(imagespace,image=stopimg,borderwidth=0,bg="#006666")
prevbt.grid(row=0,column=0)
playbt.grid(row=0,column=1)
pausebt.grid(row=0,column=2)
stopbt.grid(row=0,column=3)
nextbt.grid(row=0,column=4)
loop.mainloop()
